parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: agencia
    database_user: jmboni
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 524f87812088e3b0c156f6e057e9dd105e5ff1c1
    database_driver: pdo_mysql
    database_path: null
